  name: Build & Deploy Spring App

  on:
    push:
      branches:
        - main
  jobs:
    build-deploy:
      name: Build and deploy questions
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup JDK 17
          uses: actions/setup-java@3
          with:
            distribution: 'openjdk'
            java-version: 20

        - name: Unit Tests
          run: ./gradlew test

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v3

        - name: Build with Gradle
          run: ./gradlew build

        - name: Build the application
          run: |
            ./gradlew clean
            ./gradlew build
            
