  name: Build & Deploy Spring App

  on:
    push:
      branches:
        - master
  jobs:
    build-deploy:
      name: Build and deploy questions
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: 17

        - name: Unit Tests
          run: ./gradlew test

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v3

        - name: Build the application
          run: |
            echo "Current directory: $(pwd)"
            ls -la
            ./gradlew clean
            ./gradlew build

        - name: Build docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            dockerfile: Dockerfile
            push: false
# We set the push to false because in this step we just want to check if we can create the image or not.
            tags: ${{ secrets.DOCKER_HUB_USERNAME}}Questions-Backend:latest  #We want this tag to be dynamic
#            tags: ${{ secrets.DOCKER_HUB_USERNAME}}Questions-Backend:$(date-'%Y%m%d%H%M%S')  #We want this tag to be dynamic
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME}}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Push to Docker Hub
          uses: docker/build-push-action@v5
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            # We set the push to false because in this step we just want to check if we can create the image or not.
            tags: ${{ secrets.DOCKER_HUB_USERNAME}}Questions-Backend:latest  #We want this tag to be dynamic
#            tags: ${{ secrets.DOCKER_HUB_USERNAME}}Questions-Backend:$(date-'%Y%m%d%H%M%S')  #We want this tag to be dynamic
