  name: Build & Deploy Spring App

  on:
    push:
      branches:
        - master
  jobs:
    build-deploy:
      name: Build and deploy questions
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup JDK 17
          uses: actions/setup-java@3
          with:
            distribution: 'openjdk'
            java-version: 17

        - name: Unit Tests
          run: ./gradlew test

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v3

        - name: Build the application
          run: |
            echo "Current directory: $(pwd)"
            ls -la
            ./gradlew clean
            ./gradlew build
            
